// © 2023, ETH Zurich
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

use std::{
    hash::{Hash, Hasher},
    mem::discriminant,
};

use super::display::DisplayWithCompilerCtxt;
use crate::{
    Sealed,
    borrow_pcg::region_projection::HasTy,
    error::PlaceContainingPtrWithNestedLifetime,
    rustc_interface::{
        VariantIdx,
        ast::Mutability,
        middle::{
            mir::{Local, Place as MirPlace, PlaceElem, PlaceRef, ProjectionElem},
            ty::{self, Ty, TyKind},
        },
    },
    utils::{HasCompilerCtxt, data_structures::HashSet, json::ToJsonWithCtxt},
};
use crate::{
    borrow_pcg::{region_projection::LifetimeProjection, visitor::extract_regions},
    utils::{
        DebugCtxt,
        display::{DisplayOutput, DisplayWithCtxt, OutputMode},
        validity::HasValidityCheck,
    },
};
use derive_more::{Deref, DerefMut};

pub(crate) mod display;
pub(crate) mod expansion;
pub mod maybe_old;
pub mod maybe_remote;
pub(crate) mod ordering;
pub(crate) mod pcg_place;
pub(crate) mod place_like;
pub(crate) mod place_projectable;
pub mod remote;
pub use expansion::PlaceExpansion;
pub use ordering::PrefixRelation;
pub use pcg_place::PcgPlace;
pub use place_like::PlaceLike;
pub use place_projectable::PlaceProjectable;

/// A MIR place that can appear in PCG nodes. The place has been normalized such
/// that the regions in the type do not depend on the type contained in any of
/// `Field` projections of the type.
///
/// In particular, consider the following code:
/// ```ignore
/// struct Pair<'a>(&'a mut i32, &'a mut i32);
/// fn main() {
///   let x: Pair<'_> = Pair(&mut 1, &mut 2);
///   let y: &mut i32 = x.0;
/// }
/// ```
/// Suppose that `x` has type `Pair<'?1>`. The type of `x.0` reported by
/// Rust in the second assignment statement is in general *not* `&'?1 mut i32`,
/// but rather a type that uses a fresh instance variable (e.g. `&'?2 mut i32`).
///
/// Using `x.0` as it is obtained directly from the MIR would result in problems
/// comparing places. In particular, the expansion of `x` into `x.0` and `x.1`
/// generated by the PCG will yield places with region `&'?1` based on the type
/// of `x`. Accordingly, the `x.0` from the MIR would not be equal to the `x.0`
/// in the expansion, as their types would be different.
///
/// For this reason, PCG places cannot be constructed directly from MIR places.
/// Rather the [`Place::new`] method converts a MIR place `p` into a PCG place
/// `p'` by projecting each element of `p`'s projection using the type of the
/// underlying local.
#[derive(Clone, Copy, Deref, DerefMut)]
#[cfg_attr(feature = "type-export", derive(ts_rs::TS))]
#[cfg_attr(feature = "type-export", ts(as = "String"))]
pub struct Place<'tcx>(
    #[deref]
    #[deref_mut]
    PlaceRef<'tcx>,
);

impl<'tcx, Ctxt: Copy> DisplayWithCtxt<Ctxt> for OwnedPlace<'tcx>
where
    Place<'tcx>: DisplayWithCtxt<Ctxt>,
{
    fn display_output(&self, ctxt: Ctxt, mode: OutputMode) -> DisplayOutput {
        self.place().display_output(ctxt, mode)
    }
}

#[derive(Clone, Copy, Deref, Debug, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "type-export", derive(ts_rs::TS))]
pub struct BorrowedPlace<'tcx>(Place<'tcx>);

impl<'tcx> BorrowedPlace<'tcx> {
    pub(crate) fn place(self) -> Place<'tcx> {
        self.0
    }
}

impl<'tcx> From<BorrowedPlace<'tcx>> for Place<'tcx> {
    fn from(bp: BorrowedPlace<'tcx>) -> Self {
        bp.0
    }
}

impl Sealed for BorrowedPlace<'_> {}

impl<'tcx, Ctxt: DebugCtxt + Copy> HasValidityCheck<Ctxt> for BorrowedPlace<'tcx>
where
    Place<'tcx>: HasValidityCheck<Ctxt>,
{
    fn check_validity(&self, ctxt: Ctxt) -> Result<(), String> {
        self.0.check_validity(ctxt)
    }
}

#[derive(Clone, Copy, Deref, Debug, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "type-export", derive(ts_rs::TS))]
pub struct OwnedPlace<'tcx>(Place<'tcx>);

impl<'tcx> OwnedPlace<'tcx> {
    pub(crate) fn place(self) -> Place<'tcx> {
        self.0
    }
    pub(crate) fn parent_place(self) -> Option<Self> {
        self.0.parent_place().map(Self)
    }
}

impl From<crate::utils::mir::Local> for OwnedPlace<'_> {
    fn from(local: crate::utils::mir::Local) -> Self {
        Self(local.into())
    }
}

impl From<crate::rustc_interface::middle::mir::Local> for OwnedPlace<'_> {
    fn from(local: crate::rustc_interface::middle::mir::Local) -> Self {
        Self(local.into())
    }
}

impl serde::Serialize for OwnedPlace<'_> {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(&format!("{:?}", self.0))
    }
}

impl Sealed for Place<'_> {}

impl<'a, 'tcx: 'a, Ctxt: HasCompilerCtxt<'a, 'tcx>> HasTy<'tcx, Ctxt> for Place<'tcx> {
    fn rust_ty(&self, ctxt: Ctxt) -> ty::Ty<'tcx> {
        self.0.ty(ctxt.body(), ctxt.tcx()).ty
    }
}

impl<'a, 'tcx: 'a, Ctxt: HasCompilerCtxt<'a, 'tcx>> HasTy<'tcx, Ctxt> for BorrowedPlace<'tcx> {
    fn rust_ty(&self, ctxt: Ctxt) -> ty::Ty<'tcx> {
        self.0.rust_ty(ctxt)
    }
}

impl From<crate::utils::mir::Local> for Place<'_> {
    fn from(local: crate::utils::mir::Local) -> Self {
        (*local).into()
    }
}

impl<'tcx> From<Place<'tcx>> for PlaceRef<'tcx> {
    fn from(place: Place<'tcx>) -> Self {
        *place
    }
}

impl<'a, 'tcx: 'a, Ctxt: HasCompilerCtxt<'a, 'tcx>> ToJsonWithCtxt<Ctxt> for Place<'tcx> {
    fn to_json(&self, ctxt: Ctxt) -> serde_json::Value {
        serde_json::Value::String(self.display_string(ctxt))
    }
}

pub trait PcgNodeComponent = Copy + Eq + std::hash::Hash + std::fmt::Debug;

/// A trait for PCG nodes that contain a single place.
pub trait HasPlace<'tcx, P = Place<'tcx>>: Sized {
    fn is_place(&self) -> bool;

    fn place(&self) -> P;

    fn place_mut(&mut self) -> &mut P;
}

impl<'tcx> HasPlace<'tcx> for Place<'tcx> {
    fn place(&self) -> Place<'tcx> {
        *self
    }
    fn place_mut(&mut self) -> &mut Place<'tcx> {
        self
    }

    fn is_place(&self) -> bool {
        true
    }
}

impl<'tcx> Place<'tcx> {
    #[rustversion::since(2025-03-01)]
    pub(crate) fn is_raw_ptr<'a>(&self, ctxt: impl HasCompilerCtxt<'a, 'tcx>) -> bool
    where
        'tcx: 'a,
    {
        self.ty(ctxt).ty.is_raw_ptr()
    }

    #[rustversion::before(2025-03-01)]
    pub(crate) fn is_raw_ptr<'a>(&self, ctxt: impl HasCompilerCtxt<'a, 'tcx>) -> bool
    where
        'tcx: 'a,
    {
        self.rust_ty(ctxt).is_unsafe_ptr()
    }

    pub(crate) fn parent_place(self) -> Option<Self> {
        let (prefix, _) = self.last_projection()?;
        Some(prefix)
    }
}

impl<'tcx> Place<'tcx> {
    pub(crate) fn as_owned_place<'a>(
        self,
        ctxt: impl HasCompilerCtxt<'a, 'tcx>,
    ) -> Option<OwnedPlace<'tcx>>
    where
        'tcx: 'a,
    {
        if self.is_owned(ctxt) {
            Some(OwnedPlace(self))
        } else {
            None
        }
    }

    pub(crate) fn expect_borrowed_place<'a>(
        self,
        ctxt: impl HasCompilerCtxt<'a, 'tcx>,
    ) -> BorrowedPlace<'tcx>
    where
        'tcx: 'a,
    {
        self.as_borrowed_place(ctxt).unwrap_or_else(|| {
            unreachable!(
                "Expected borrowed place, got owned place {} with type {:?}",
                self.display_string(ctxt),
                self.rust_ty(ctxt)
            )
        })
    }

    pub(crate) fn as_borrowed_place<'a>(
        self,
        ctxt: impl HasCompilerCtxt<'a, 'tcx>,
    ) -> Option<BorrowedPlace<'tcx>>
    where
        'tcx: 'a,
    {
        if !self.is_owned(ctxt) {
            Some(BorrowedPlace(self))
        } else {
            None
        }
    }

    pub(crate) fn new_unchecked(local: Local, projection: &'tcx [PlaceElem<'tcx>]) -> Self {
        Self(PlaceRef { local, projection })
    }

    pub(crate) fn from_mir_place<'a>(
        place: MirPlace<'tcx>,
        ctxt: impl HasCompilerCtxt<'a, 'tcx>,
    ) -> Self
    where
        'tcx: 'a,
    {
        Self::new(place.local, place.projection, ctxt)
    }

    #[must_use]
    pub fn new<'a>(
        local: Local,
        projection: &'tcx [PlaceElem<'tcx>],
        ctxt: impl HasCompilerCtxt<'a, 'tcx>,
    ) -> Self
    where
        'tcx: 'a,
    {
        let mut place: Self = local.into();
        for elem in projection {
            place = place.project_elem(*elem, ctxt).unwrap();
        }
        place
    }

    pub(crate) fn base_lifetime_projection<'a>(
        self,
        ctxt: impl HasCompilerCtxt<'a, 'tcx>,
    ) -> Option<LifetimeProjection<'tcx, Self>>
    where
        'tcx: 'a,
    {
        self.ty_region(ctxt)
            .map(|region| LifetimeProjection::new(self, region, None, ctxt.ctxt()).unwrap())
    }

    #[must_use]
    pub fn projection(&self) -> &'tcx [PlaceElem<'tcx>] {
        self.0.projection
    }

    pub(crate) fn contains_unsafe_deref<'a>(&self, ctxt: impl HasCompilerCtxt<'a, 'tcx>) -> bool
    where
        'tcx: 'a,
    {
        for (p, proj) in self.iter_projections(ctxt.ctxt()) {
            if p.is_raw_ptr(ctxt) && matches!(proj, PlaceElem::Deref) {
                return true;
            }
        }
        false
    }

    pub(crate) fn is_enum<'a>(&self, ctxt: impl HasCompilerCtxt<'a, 'tcx>) -> bool
    where
        'tcx: 'a,
    {
        self.ty(ctxt).ty.is_enum()
    }

    pub(crate) fn check_lifetimes_under_unsafe_ptr<'a>(
        self,
        ctxt: impl HasCompilerCtxt<'a, 'tcx>,
    ) -> std::result::Result<(), PlaceContainingPtrWithNestedLifetime<'tcx>>
    where
        'tcx: 'a,
    {
        fn ty_has_lifetimes_under_unsafe_ptr<'a, 'tcx>(
            ty: Ty<'tcx>,
            seen: &mut HashSet<Ty<'tcx>>,
            ctxt: impl HasCompilerCtxt<'a, 'tcx>,
        ) -> std::result::Result<(), Vec<ty::Ty<'tcx>>>
        where
            'tcx: 'a,
        {
            if seen.contains(&ty) {
                return Ok(());
            }
            seen.insert(ty);
            if extract_regions(ty).is_empty() {
                return Ok(());
            }
            #[rustversion::before(2025-03-01)]
            let is_raw_ptr = ty.is_unsafe_ptr();
            #[rustversion::since(2025-03-01)]
            let is_raw_ptr = ty.is_raw_ptr();
            if is_raw_ptr {
                return std::result::Result::Err(vec![ty]);
            }
            let field_tys: Vec<Ty<'tcx>> = match ty.kind() {
                TyKind::Array(ty, _) | TyKind::Slice(ty) | TyKind::Ref(_, ty, _) => vec![*ty],
                TyKind::Adt(def, substs) => {
                    if ty.is_box() {
                        vec![substs.first().unwrap().expect_ty()]
                    } else {
                        def.all_fields()
                            .map(|f| f.ty(ctxt.tcx(), substs))
                            .collect::<Vec<_>>()
                    }
                }
                TyKind::Tuple(slice) => slice.iter().collect::<Vec<_>>(),
                TyKind::Closure(_, substs) => {
                    substs.as_closure().upvar_tys().iter().collect::<Vec<_>>()
                }
                TyKind::Coroutine(_, _) | TyKind::CoroutineClosure(_, _) | TyKind::FnDef(_, _) => {
                    vec![]
                }
                TyKind::Alias(_, _)
                | TyKind::Dynamic(..)
                | TyKind::Param(_)
                | TyKind::Bound(_, _)
                | TyKind::CoroutineWitness(_, _) => vec![],
                _ => todo!(),
            };
            for ty in field_tys {
                if let Err(mut tys) = ty_has_lifetimes_under_unsafe_ptr(ty, seen, ctxt) {
                    tys.push(ty);
                    return Err(tys);
                }
            }
            Ok(())
        }
        ty_has_lifetimes_under_unsafe_ptr(self.rust_ty(ctxt), &mut HashSet::default(), ctxt)
            .map_err(|tys| PlaceContainingPtrWithNestedLifetime {
                place: self,
                invalid_ty_chain: tys,
            })
    }

    pub fn is_mut_ref<'a>(&self, ctxt: impl HasCompilerCtxt<'a, 'tcx>) -> bool
    where
        'tcx: 'a,
    {
        matches!(
            self.0.ty(ctxt.body(), ctxt.tcx()).ty.kind(),
            TyKind::Ref(_, _, Mutability::Mut)
        )
    }

    pub fn is_shared_ref<'a>(self, ctxt: impl HasCompilerCtxt<'a, 'tcx>) -> bool
    where
        'tcx: 'a,
    {
        matches!(self.ref_mutability(ctxt), Some(Mutability::Not))
    }

    pub fn is_ref<'a>(self, ctxt: impl HasCompilerCtxt<'a, 'tcx>) -> bool
    where
        'tcx: 'a,
    {
        self.0.ty(ctxt.body(), ctxt.tcx()).ty.is_ref()
    }

    pub fn ref_mutability<'a>(&self, ctxt: impl HasCompilerCtxt<'a, 'tcx>) -> Option<Mutability>
    where
        'tcx: 'a,
    {
        self.0.ty(ctxt.body(), ctxt.tcx()).ty.ref_mutability()
    }

    #[must_use]
    pub fn common_prefix(self, other: Self) -> Self {
        assert_eq!(self.local, other.local);

        let max_len = std::cmp::min(self.projection.len(), other.projection.len());
        let common_prefix = self
            .compare_projections(other)
            .position(|(eq, _, _)| !eq)
            .unwrap_or(max_len);
        Self::new_unchecked(self.local, &self.projection[..common_prefix])
    }

    #[must_use]
    pub fn joinable_to(self, to: Self) -> Self {
        assert!(self.is_prefix_of(to));
        let diff = to.projection.len() - self.projection.len();
        let to_proj = self.projection.len()
            + to.projection[self.projection.len()..]
                .iter()
                .position(|p| !matches!(p, ProjectionElem::Deref | ProjectionElem::Field(..)))
                .unwrap_or(diff);
        Self::new_unchecked(self.local, &to.projection[..to_proj])
    }

    #[must_use]
    pub fn last_projection(self) -> Option<(Self, PlaceElem<'tcx>)> {
        self.0
            .last_projection()
            .map(|(place, proj)| (Place::new_unchecked(place.local, place.projection), proj))
    }

    #[must_use]
    pub fn last_projection_ty(self) -> Option<Ty<'tcx>> {
        self.last_projection().and_then(|(_, proj)| match proj {
            ProjectionElem::Field(_, ty) | ProjectionElem::OpaqueCast(ty) => Some(ty),
            _ => None,
        })
    }

    #[must_use]
    pub fn is_deref_of(self, other: Self) -> bool {
        self.projection.last() == Some(&ProjectionElem::Deref)
            && other.is_prefix_of(self)
            && other.projection.len() == self.projection.len() - 1
    }

    #[must_use]
    pub fn is_downcast_of(self, other: Self) -> Option<VariantIdx> {
        if let Some(ProjectionElem::Downcast(_, index)) = self.projection.last() {
            if other.is_prefix_of(self) && other.projection.len() == self.projection.len() - 1 {
                Some(*index)
            } else {
                None
            }
        } else {
            None
        }
    }

    pub(crate) fn iter_projections_after<'a>(
        self,
        other: Self,
        ctxt: impl HasCompilerCtxt<'a, 'tcx>,
    ) -> Option<impl Iterator<Item = (Self, PlaceElem<'tcx>)>>
    where
        'tcx: 'a,
    {
        if other.is_prefix_of(self) {
            Some(
                self.iter_projections(ctxt.ctxt())
                    .into_iter()
                    .skip(other.projection.len()),
            )
        } else {
            None
        }
    }

    #[must_use]
    pub fn is_deref(self) -> bool {
        self.projection.last() == Some(&ProjectionElem::Deref)
    }

    #[must_use]
    pub fn nearest_owned_place<'a>(self, ctxt: impl HasCompilerCtxt<'a, 'tcx>) -> Self
    where
        'tcx: 'a,
    {
        if self.is_owned(ctxt) {
            return self;
        }
        for (place, _) in self.iter_projections(ctxt).into_iter().rev() {
            if place.is_owned(ctxt) {
                return place;
            }
        }
        unreachable!()
    }

    pub(crate) fn is_prefix_or_postfix_of(self, other: Self) -> bool {
        self.is_prefix_of(other) || other.is_prefix_of(self)
    }
}

impl Hash for Place<'_> {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.0.local.hash(state);
        let projection = self.0.projection;
        for &pe in projection {
            match pe {
                ProjectionElem::Field(field, _) => {
                    discriminant(&pe).hash(state);
                    field.hash(state);
                }
                ProjectionElem::Downcast(_, variant) => {
                    discriminant(&pe).hash(state);
                    variant.hash(state);
                }
                _ => pe.hash(state),
            }
        }
    }
}

impl From<Local> for Place<'_> {
    fn from(value: Local) -> Self {
        Self::new_unchecked(value, &[])
    }
}
