// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayOutput } from "./DisplayOutput";

/**
 * A pair of a PCG action and a debug context (indicating the source of the
 * action and possibly its effects).
 */
export type ActionKindWithDebugInfo<T, DebugInfo = DisplayOutput | null> = { kind: T, debug_info: DebugInfo, };
