// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionKindWithDebugInfo } from "./ActionKindWithDebugInfo";
import type { ApplyActionResult } from "./ApplyActionResult";
import type { BorrowPcgActionKindDebugRepr } from "./BorrowPcgActionKindDebugRepr";
import type { GenericPcgAction } from "./GenericPcgAction";
import type { RepackOp } from "./RepackOp";

export type AppliedAction = { action: GenericPcgAction<ActionKindWithDebugInfo<BorrowPcgActionKindDebugRepr, string | null>, ActionKindWithDebugInfo<RepackOp, string | null>>, result: ApplyActionResult<string>, _marker: null, };
