// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayOutput } from "./DisplayOutput";

/**
 * The result of applying an action to the PCG.
 */
export type ApplyActionResult<Summary = DisplayOutput> = { 
/**
 * Whether the action had any effect on the PCG state.
 */
changed: boolean, 
/**
 * A summary of the changes made by the action.
 */
change_summary: Summary, };
