// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasicBlock } from "./BasicBlock";
import type { EvalStmtPhase } from "./EvalStmtPhase";

export type DataflowStmtPhase = "Initial" | { "EvalStmt": EvalStmtPhase } | { "Join": BasicBlock };
