// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourcePos } from "./SourcePos";

export type FunctionMetadata = { name: string, signature: string, debug_signature: string, source: string, start: SourcePos, };
