// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GenericPcgAction<Borrow, Owned> = { "type": "Borrow", "data": Borrow } | { "type": "Owned", "data": Owned };
