// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MirEdge } from "./MirEdge";
import type { MirNode } from "./MirNode";

export type MirGraph = { nodes: Array<MirNode>, edges: Array<MirEdge>, };
