// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MirStmt } from "./MirStmt";

export type MirNode = { id: string, block: number, stmts: Array<MirStmt>, terminator: MirStmt, };
