// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasicBlock } from "./BasicBlock";
import type { PcgStmtVisualizationData } from "./PcgStmtVisualizationData";
import type { PcgSuccessorVisualizationData } from "./PcgSuccessorVisualizationData";

export type PcgBlockVisualizationData = { statements: Array<PcgStmtVisualizationData>, successors: { [key in BasicBlock]: PcgSuccessorVisualizationData }, };
