// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PcgDebugDataForBlock } from "./PcgDebugDataForBlock";

export type PcgBlockDebugData = { dot_output_dir: string, dot_graphs: PcgDebugDataForBlock, };
