// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PcgLoopDebugData } from "./PcgLoopDebugData";
import type { StmtGraphs } from "./StmtGraphs";
import type { StringOf } from "./StringOf";

export type PcgDebugDataForBlock = { loop_data: PcgLoopDebugData | null, graphs: Array<StmtGraphs<StringOf>>, };
