// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaceUsages } from "./PlaceUsages";

export type PcgLoopDebugData = { used_places: PlaceUsages, live_loop_places: PlaceUsages, };
