// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaceLabelReplacement } from "./PlaceLabelReplacement";
import type { PlaceUsages } from "./PlaceUsages";

export type PcgLoopDebugData = { used_places: PlaceUsages, live_loop_places: PlaceUsages,
/**
 * List of (graph_name, dot_output) pairs for debug dot graphs.
 */
dot_graphs: Array<[string, string]>, loop_blocked_places: PlaceUsages, ancestors_of_live_places: Array<[string, Array<string>]>, root_places: Array<[string, Array<string>]>, loop_blocker_places: PlaceUsages,
/**
 * List of (place, replacements) for place labeling debug info.
 */
place_labels: Array<[string, Array<PlaceLabelReplacement>]>, };
