// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaceUsages } from "./PlaceUsages";

export type PcgLoopDebugData = { used_places: PlaceUsages, live_loop_places: PlaceUsages, pre_loop_dot_graph: string, abstraction_dot_graph: string, subgraph_to_cut_dot_graph: string, loop_blocked_places: PlaceUsages, root_places: Array<[string, Array<string>]>, loop_blocker_places: PlaceUsages, };
