// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppliedAction } from "./AppliedAction";
import type { EvalStmtData } from "./EvalStmtData";
import type { StmtGraphs } from "./StmtGraphs";
import type { StringOf } from "./StringOf";

export type PcgStmtVisualizationData = { actions: EvalStmtData<Array<AppliedAction>>, graphs: StmtGraphs<StringOf>, };
