// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasicBlock } from "./BasicBlock";
import type { PcgBlockVisualizationData } from "./PcgBlockVisualizationData";

export type PcgVisualizationData = { [key in BasicBlock]: PcgBlockVisualizationData };
