// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A place label replacement from→to for debug visualization.
 */
export type PlaceLabelReplacement = { from: string, to: string, };
