// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The way in which a place is used inside a loop.
 *
 * These are the usage types $M = \{R, W, E\}$ of the loop invariant
 * capability calculation. `Exclusive` is the top element of the
 * meet-semilattice; `Read` and `Write` are incomparable, and their join is
 * `Exclusive`.
 */
export type PlaceUsageType = "Read" | "Write" | "Exclusive";
