// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaceUsageType } from "./PlaceUsageType";

/**
 * Serializable representation of place usages for visualization.
 */
export type PlaceUsagesDebugRepr = { usages: { [key in string]: PlaceUsageType }, };
