// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaceUsageType } from "./PlaceUsageType";

export type PlaceUsages = { usages: { [key in string]: PlaceUsageType }, _marker: null, };
