// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A MIR place that can appear in PCG nodes. The place has been normalized such
 * that the regions in the type do not depend on the type contained in any of
 * `Field` projections of the type.
 *
 * In particular, consider the following code:
 * ```ignore
 * struct Pair<'a>(&'a mut i32, &'a mut i32);
 * fn main() {
 *   let x: Pair<'_> = Pair(&mut 1, &mut 2);
 *   let y: &mut i32 = x.0;
 * }
 * ```
 * Suppose that `x` has type `Pair<'?1>`. The type of `x.0` reported by
 * Rust in the second assignment statement is in general *not* `&'?1 mut i32`,
 * but rather a type that uses a fresh instance variable (e.g. `&'?2 mut i32`).
 *
 * Using `x.0` as it is obtained directly from the MIR would result in problems
 * comparing places. In particular, the expansion of `x` into `x.0` and `x.1`
 * generated by the PCG will yield places with region `&'?1` based on the type
 * of `x`. Accordingly, the `x.0` from the MIR would not be equal to the `x.0`
 * in the expansion, as their types would be different.
 *
 * For this reason, PCG places cannot be constructed directly from MIR places.
 * Rather the [`Place::new`] method converts a MIR place `p` into a PCG place
 * `p'` by projecting each element of `p`'s projection using the type of the
 * underlying local.
 */
export type Place = string;
