// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityKind } from "./CapabilityKind";

export type RegainedCapability<Place> = { place: Place, capability: CapabilityKind, };
