// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OwnedCapability } from "./OwnedCapability";
import type { OwnedPlace } from "./OwnedPlace";
import type { Place } from "./Place";
import type { RegainedCapability } from "./RegainedCapability";
import type { RepackCollapse } from "./RepackCollapse";
import type { RepackExpand } from "./RepackExpand";
import type { RepackType } from "./RepackType";
import type { Weaken } from "./Weaken";

export type RepackOp = { "type": "StorageDead", "data": string } | { "type": "IgnoreStorageDead", "data": string } | { "type": "Weaken", "data": Weaken<OwnedPlace, OwnedCapability, OwnedCapability> } | { "type": "Expand", "data": RepackExpand<RepackType> } | { "type": "Collapse", "data": RepackCollapse<Place> } | { "type": "DerefShallowInit", "data": [Place, Place] } | { "type": "RegainLoanedCapability", "data": RegainedCapability<Place> };
