// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityKind } from "./CapabilityKind";
import type { Place } from "./Place";

export type RepackCollapse<P = Place> = { to: P, capability: CapabilityKind, guide: string | null, };
