// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeMutability } from "./EdgeMutability";

export type RepackType = "Real" | { "Materialized": EdgeMutability };
