// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DotFileAtPhase } from "./DotFileAtPhase";
import type { EvalStmtData } from "./EvalStmtData";

export type StmtGraphs = { at_phase: Array<DotFileAtPhase<string>>, actions: EvalStmtData<Array<string>>, };
