// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DotFileAtPhase } from "./DotFileAtPhase";
import type { EvalStmtData } from "./EvalStmtData";
import type { PathToDotFile } from "./PathToDotFile";
import type { StringOf } from "./StringOf";

export type StmtGraphs<PhaseKey = StringOf> = { at_phase: Array<DotFileAtPhase<PhaseKey>>, actions: EvalStmtData<Array<PathToDotFile>>, };
