// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityKind } from "./CapabilityKind";
import type { Place } from "./Place";

/**
 * Instructs that the current capability to the place (first [`CapabilityKind`]) should
 * be weakened to the second given capability. We guarantee that `_.1 > _.2`.
 * If `_.2` is `None`, the capability is removed.
 */
export type Weaken<P = Place, FromCap = CapabilityKind, ToCap = CapabilityKind> = { place: P, from: FromCap, to: ToCap, };
