// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityKind } from "./CapabilityKind";

/**
 * Instructs that the current capability to the place (first [`CapabilityKind`]) should
 * be weakened to the second given capability. We guarantee that `_.1 > _.2`.
 * If `_.2` is `None`, the capability is removed.
 */
export type Weaken<ToCap = CapabilityKind | null> = { place: string, from: CapabilityKind, to: ToCap, 
/**
 * Temporary flag indicating this Weaken was emitted due to a `StorageDead`.
 * Required until <https://github.com/prusti/pcg/issues/137> is resolved.
 */
for_storage_dead: boolean, };
